# Site settings
title: Just Some Stuff
email: minshalljg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just some stuff, maybe a thing or two on development and the
  language of the week I'm trying out...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: minshalljg
github_username: minshallj

# Build settings
markdown: kramdown
